import type { Quiz } from "../types";

export const finalCertificationAssessment: Quiz = {
  id: "final-certification-assessment",
  title: "Final Certification Assessment",
  description: "25 questions covering all 5 modules. Score 80% or higher to earn your Beige Sales Rep Certification and clearance to take live leads.",
  moduleIds: ["module-1", "module-2", "module-3", "module-4"],
  passThreshold: 0.8,
  resetModules: "by-missed-question",
  isFinal: true,
  timeLimitSeconds: 2400,
  heroImage: "/images/certification-badge.png",
  questions: [
    // ---- Module 1: Welcome, Platform, Role, Traction ----
    {
      id: "fc-1",
      moduleId: "module-1",
      type: "multi",
      topicImage: "/images/icon-pipeline-flow.png",
      prompt: "What are Beige's three core platform pillars? (Select all that apply.)",
      options: [
        { id: "a", text: "Beige Marketplace" },
        { id: "b", text: "Beige OS" },
        { id: "c", text: "Beige AI" },
        { id: "d", text: "Beige Studios Network" },
      ],
      correctOptionIds: ["a", "b", "c"],
      explanation: "Beige is built on three pillars: the Marketplace (instant booking), Beige OS (the production operating system), and Beige AI (the intelligence layer for training and deal closing).",
    },
    {
      id: "fc-2",
      moduleId: "module-1",
      type: "single",
      topicImage: "/images/icon-pricing-scale.png",
      prompt: "What is the Beige Marketplace's Q2 revenue goal?",
      options: [
        { id: "a", text: "$100,000 per month" },
        { id: "b", text: "$500,000 per month" },
        { id: "c", text: "$1 million per month" },
        { id: "d", text: "$10 million per month" },
      ],
      correctOptionId: "c",
      explanation: "The stated Q2 goal is $1 million per month in the Beige Marketplace.",
    },
    {
      id: "fc-3",
      moduleId: "module-1",
      type: "single",
      topicImage: "/images/icon-payment.png",
      prompt: "What daily target should you be aiming for in closed business as a new sales rep?",
      options: [
        { id: "a", text: "$1,000" },
        { id: "b", text: "$5,000" },
        { id: "c", text: "$10,000" },
        { id: "d", text: "$25,000" },
      ],
      correctOptionId: "c",
      explanation: "The team's daily target is $10,000 in closed business.",
    },
    {
      id: "fc-4",
      moduleId: "module-1",
      type: "multi",
      topicImage: "/images/icon-event-corporate.png",
      prompt: "Which brands has Beige worked with? (Select all that apply.)",
      options: [
        { id: "a", text: "Amazon" },
        { id: "b", text: "Rolls Royce" },
        { id: "c", text: "McDonald's" },
        { id: "d", text: "Tesla" },
      ],
      correctOptionIds: ["a", "b", "c"],
      explanation: "Beige's brand client list includes Amazon, McDonald's, Walmart, Rolls Royce, Chase, Orange Theory, and DHL.",
    },
    {
      id: "fc-5",
      moduleId: "module-1",
      type: "single",
      topicImage: "/images/icon-security-lock.png",
      prompt: "What keeps Beige's no-show rate below 0.5%?",
      options: [
        { id: "a", text: "Charging a large deposit" },
        { id: "b", text: "A matchmaking algorithm plus a backup-crew guarantee" },
        { id: "c", text: "Only working with in-house staff" },
        { id: "d", text: "Requiring 30-day advance booking" },
      ],
      correctOptionId: "b",
      explanation: "The matchmaking algorithm and the Beige Guarantee's always-on-standby backup crews keep the no-show rate under 0.5%.",
    },
    {
      id: "fc-6",
      moduleId: "module-1",
      type: "single",
      topicImage: "/images/icon-team-rotation.png",
      prompt: "What is one way sales reps can build recurring income beyond closing shoots?",
      options: [
        { id: "a", text: "The affiliate dashboard, by referring client advocates" },
        { id: "b", text: "Overtime pay" },
        { id: "c", text: "Managing production crews" },
        { id: "d", text: "There is no path to recurring income" },
      ],
      correctOptionId: "a",
      explanation: "The affiliate dashboard lets reps build a network of client advocates and earn recurring revenue tied to the clients they onboard.",
    },

    // ---- Module 2: Tools & Systems ----
    {
      id: "fc-7",
      moduleId: "module-2",
      type: "single",
      topicImage: "/images/icon-lead-inquiry.png",
      prompt: "What's the very first thing you should do when a new Thumbtack lead arrives?",
      options: [
        { id: "a", text: "Respond to it immediately, before any other task" },
        { id: "b", text: "Log it in GHL first" },
        { id: "c", text: "Wait for team confirmation" },
        { id: "d", text: "Check the client's social media" },
      ],
      correctOptionId: "a",
      explanation: "New leads always come first — respond before doing anything else.",
    },
    {
      id: "fc-8",
      moduleId: "module-2",
      type: "single",
      topicImage: "/images/icon-pipeline-flow.png",
      prompt: "A rep says they can't see a lead in GHL that should be theirs. What's the most likely cause and the fix?",
      options: [
        { id: "a", text: "The Owner field is empty — go to the lead and set the rep as Owner" },
        { id: "b", text: "GHL is down — just wait it out" },
        { id: "c", text: "The rep needs Superadmin access to see any lead" },
        { id: "d", text: "The lead was automatically deleted" },
      ],
      correctOptionId: "a",
      explanation: "This is the most common GHL access issue: an empty Owner field. Set the rep as Owner (or add them as a Follower) and the lead appears in their private pipeline.",
    },
    {
      id: "fc-9",
      moduleId: "module-2",
      type: "single",
      topicImage: "/images/icon-team-comms.png",
      prompt: "Which platform is used for Inbound Sales team communication only?",
      options: [
        { id: "a", text: "Discord" },
        { id: "b", text: "Slack" },
        { id: "c", text: "OpenPhone" },
        { id: "d", text: "GHL" },
      ],
      correctOptionId: "b",
      explanation: "Slack is reserved for Inbound Sales; everything else (production, post, UserSuccess) runs through Discord.",
    },
    {
      id: "fc-10",
      moduleId: "module-2",
      type: "single",
      topicImage: "/images/icon-payment.png",
      prompt: "For a standard (non-corporate, non-rush) booking, what's the payment structure?",
      options: [
        { id: "a", text: "100% upfront" },
        { id: "b", text: "50% deposit, remainder due 3 days before the shoot" },
        { id: "c", text: "25% deposit, remainder due after the shoot" },
        { id: "d", text: "No deposit required" },
      ],
      correctOptionId: "b",
      explanation: "Standard policy: 50% deposit to lock the date, remainder due 3 days before the shoot.",
    },
    {
      id: "fc-11",
      moduleId: "module-2",
      type: "single",
      topicImage: "/images/icon-lead-inquiry.png",
      prompt: "What color indicator in OpenPhone flags a pending client (50% paid or strong intent)?",
      options: [
        { id: "a", text: "Red" },
        { id: "b", text: "Green" },
        { id: "c", text: "Yellow" },
        { id: "d", text: "Blue" },
      ],
      correctOptionId: "c",
      explanation: "Yellow marks a pending client — 50% paid or clearly showing strong intent to book.",
    },
    {
      id: "fc-12",
      moduleId: "module-2",
      type: "single",
      topicImage: "/images/icon-payment.png",
      prompt: "A client just signed their beige.app quote and asked how to pay. What do you send?",
      options: [
        { id: "a", text: "The Zelle email or @beigecorp tag, directly over text" },
        { id: "b", text: "A HoneyBook payment link with an access code" },
        { id: "c", text: "Nothing — wait for accounting to reach out" },
        { id: "d", text: "A separate Invoice Simple estimate" },
      ],
      correctOptionId: "a",
      explanation: "Payment now runs through Zelle (accounting@beigecorporation.io or @beigecorp) sent directly over text once the beige.app quote is signed — no separate invoicing or payment-link tool involved.",
    },

    // ---- Module 3: Call Scripts & Event Types ----
    {
      id: "fc-13",
      moduleId: "module-3",
      type: "ordering",
      topicImage: "/images/icon-checklist-verify.png",
      prompt: "Put the Universal Call Script Framework in order.",
      steps: ["Intro", "Value Propositions", "Discovery Questions", "Wrap-Up", "Closing"],
      explanation: "Every call follows: Intro, Value Propositions, Discovery Questions, Wrap-Up, Closing — regardless of event type.",
    },
    {
      id: "fc-14",
      moduleId: "module-3",
      type: "single",
      topicImage: "/images/icon-event-wedding.png",
      prompt: "What are the two standard wedding video length options?",
      options: [
        { id: "a", text: "30–60 seconds or 1–2 minutes" },
        { id: "b", text: "4–7 minute highlight or 20–30 minute feature" },
        { id: "c", text: "5–10 minute short film" },
        { id: "d", text: "Full-length ceremony only" },
      ],
      correctOptionId: "b",
      explanation: "Weddings offer a 4–7 minute highlight video or a 20–30 minute feature — most clients want both.",
    },
    {
      id: "fc-15",
      moduleId: "module-3",
      type: "single",
      topicImage: "/images/icon-event-music.png",
      prompt: "What is the starting price for a music video?",
      options: [
        { id: "a", text: "$1,500" },
        { id: "b", text: "$2,500" },
        { id: "c", text: "$5,000" },
        { id: "d", text: "$500" },
      ],
      correctOptionId: "b",
      explanation: "Music videos start at $2,500 — know your floor before negotiating down.",
    },
    {
      id: "fc-16",
      moduleId: "module-3",
      type: "single",
      topicImage: "/images/icon-hybrid-creator.png",
      prompt: "A client asks for just photography at their Quinceañera. What's the right move?",
      options: [
        { id: "a", text: "Accept immediately, no upsell" },
        { id: "b", text: "Offer a discounted package deal for both video and photo" },
        { id: "c", text: "Tell them photo-only isn't offered" },
        { id: "d", text: "Redirect them to a competitor" },
      ],
      correctOptionId: "b",
      explanation: "Always offer the discounted video + photo package deal before accepting a single-service booking.",
    },
    {
      id: "fc-17",
      moduleId: "module-3",
      type: "single",
      topicImage: "/images/icon-event-memorial.png",
      prompt: "What tone governs the entire memorial script?",
      options: [
        { id: "a", text: "Fast and efficient" },
        { id: "b", text: "Compassionate, unhurried, never pushy about budget or dates" },
        { id: "c", text: "Celebratory and upbeat" },
        { id: "d", text: "Strictly formal" },
      ],
      correctOptionId: "b",
      explanation: "Memorials are the most emotionally sensitive script — compassionate, unhurried, never pushy.",
    },
    {
      id: "fc-18",
      moduleId: "module-3",
      type: "single",
      topicImage: "/images/icon-pricing-scale.png",
      prompt: "What's the Holiday Clause?",
      options: [
        { id: "a", text: "A 20% holiday surcharge" },
        { id: "b", text: "No additional charge for booking on a holiday" },
        { id: "c", text: "Holidays are blacked out from booking" },
        { id: "d", text: "Only corporate clients can book holidays" },
      ],
      correctOptionId: "b",
      explanation: "Unlike most competitors, Beige charges nothing extra for holiday dates — use it as a closer.",
    },
    {
      id: "fc-19",
      moduleId: "module-3",
      type: "single",
      topicImage: "/images/icon-event-corporate.png",
      prompt: "Roughly how many edited photos per hour should a corporate client expect?",
      options: [
        { id: "a", text: "10" },
        { id: "b", text: "25" },
        { id: "c", text: "50" },
        { id: "d", text: "100" },
      ],
      correctOptionId: "c",
      explanation: "About 50 edited photos per hour of coverage is the standard to quote.",
    },

    // ---- Module 4: Objection Handling & Live Scenarios ----
    {
      id: "fc-20",
      moduleId: "module-4",
      type: "single",
      topicImage: "/images/icon-pricing-scale.png",
      prompt: "What's the maximum discount a rep may ever offer off the pricing calculator?",
      options: [
        { id: "a", text: "10%" },
        { id: "b", text: "15%" },
        { id: "c", text: "20%" },
        { id: "d", text: "No fixed limit" },
      ],
      correctOptionId: "c",
      explanation: "20% off the pricing calculator output is the hard ceiling — never exceed it.",
    },
    {
      id: "fc-21",
      moduleId: "module-4",
      type: "single",
      topicImage: "/images/icon-checklist-verify.png",
      prompt: "A client says \"the price is too high.\" What's the correct first move?",
      options: [
        { id: "a", text: "Offer the maximum discount immediately" },
        { id: "b", text: "Break down the scope and reframe the value" },
        { id: "c", text: "Tell them to look elsewhere if it's too much" },
        { id: "d", text: "End the call" },
      ],
      correctOptionId: "b",
      explanation: "Acknowledge, break down what's included, then reframe the value — discount is the last lever, not the first.",
    },
    {
      id: "fc-22",
      moduleId: "module-4",
      type: "single",
      topicImage: "/images/icon-checklist-verify.png",
      prompt: "What does the Golden Rule of Objections say an objection actually is?",
      options: [
        { id: "a", text: "A rejection of the deal" },
        { id: "b", text: "A question in disguise" },
        { id: "c", text: "A sign the rep failed" },
        { id: "d", text: "A request to end the call" },
      ],
      correctOptionId: "b",
      explanation: "\"An objection is not a rejection. It's a question in disguise\" — answer the real question behind it.",
    },
    {
      id: "fc-23",
      moduleId: "module-4",
      type: "multi",
      topicImage: "/images/icon-security-lock.png",
      prompt: "Which are legitimate Beige differentiators to cite against a cheaper competitor? (Select all that apply.)",
      options: [
        { id: "a", text: "$1M liability insurance" },
        { id: "b", text: "Beige Guarantee (backup crew on standby)" },
        { id: "c", text: "Raw content / IP ownership" },
        { id: "d", text: "\"We're just better\"" },
      ],
      correctOptionIds: ["a", "b", "c"],
      explanation: "Concrete proof — insurance, the Guarantee, raw content ownership — beats vague superiority claims with analytical clients.",
    },
    {
      id: "fc-24",
      moduleId: "module-4",
      type: "scenario",
      scenarioContext: "In the Wedding Budget Pushback scenario, the client says a competitor already quoted close to your discounted price.",
      characterImage: "/images/mathieu-thinking.png",
      sceneImage: "/images/scene-wedding-budget-EN.png",
      prompt: "What's the strongest response?",
      options: [
        { id: "a", text: "Match the unknown competitor price immediately" },
        { id: "b", text: "Acknowledge it, push toward — not past — the 20% ceiling, and add urgency about the date" },
        { id: "c", text: "Tell them to just book with the competitor then" },
        { id: "d", text: "Say nothing and wait for them to decide" },
      ],
      correctOptionId: "b",
      explanation: "Acknowledge the comparison, move toward your 20% ceiling without exceeding it, and layer in real urgency about the date — the combination that actually closes.",
    },
    {
      id: "fc-25",
      moduleId: "module-4",
      type: "single",
      topicImage: "/images/icon-urgency-clock.png",
      prompt: "What's a \"soft hold,\" and when should you use it?",
      options: [
        { id: "a", text: "Refusing to reserve a date without a deposit" },
        { id: "b", text: "Reserving a date informally for a hesitant client while keeping urgency and a timeline alive" },
        { id: "c", text: "Putting a client on hold mid-call" },
        { id: "d", text: "A discount applied automatically to every hold" },
      ],
      correctOptionId: "b",
      explanation: "The soft hold assumes the sale despite a barrier — it reserves the date informally and keeps a concrete follow-up timeline in place instead of letting the lead go cold.",
    },
  ],
};
