import type { Quiz } from "../types";

export const quizToolsWorkflow: Quiz = {
  id: "quiz-tools-workflow",
  title: "Tools & Workflow Quiz",
  description: "10 questions on the lead-to-cash workflow: Thumbtack, OpenPhone, Invoice Simple, HubSpot, and team communication.",
  moduleIds: ["module-2"],
  passThreshold: 0.8,
  resetModules: ["module-2"],
  questions: [
    {
      id: "tw-1",
      moduleId: "module-2",
      type: "ordering",
      prompt: "Put the Lead Hit Funnel steps in the correct order, from a new lead arriving to a call being scheduled.",
      steps: [
        "Lead arrives via Thumbtack",
        "Notify the Inbound Slack channel — team decides to take the lead",
        "Apply the correct template text and categorize the shoot type",
        "Assign a rep in OpenPhone and schedule the discovery call",
      ],
      explanation: "This is the exact 4-step Lead Hit Funnel: the lead lands, the team claims it in Slack, the rep applies the right template, then a rep is assigned and the discovery call gets booked.",
    },
    {
      id: "tw-2",
      moduleId: "module-2",
      type: "single",
      prompt: "A new Thumbtack lead just came in. What should you do before anything else?",
      options: [
        { id: "a", text: "Finish your current follow-up call first, then respond" },
        { id: "b", text: "Respond to the new lead immediately, before any other task" },
        { id: "c", text: "Wait for Kawser to assign it to you" },
        { id: "d", text: "Check HubSpot to see if it's a repeat client first" },
      ],
      correctOptionId: "b",
      explanation: "The key policy is: always respond to new leads before doing anything else. Speed on first contact is everything.",
    },
    {
      id: "tw-3",
      moduleId: "module-2",
      type: "matching",
      prompt: "Match each communication platform to its correct use at Beige.",
      pairs: [
        { left: "Slack", right: "Inbound Sales team communication only" },
        { left: "Discord", right: "UserSuccess, production, and post-production communication" },
        { left: "OpenPhone", right: "Client-facing calls and texts" },
        { left: "HubSpot", right: "Deal tracking and CRM records" },
      ],
      explanation: "Slack is reserved for Inbound Sales; everything else (UserSuccess, production, post-production) runs through Discord. OpenPhone is the client-facing line, HubSpot is the CRM.",
    },
    {
      id: "tw-4",
      moduleId: "module-2",
      type: "single",
      prompt: "What is the correct HubSpot deal naming format?",
      options: [
        { id: "a", text: "Client Name + Event Date + Rep Name" },
        { id: "b", text: "Event Date + Client Name + Event Type + Services" },
        { id: "c", text: "Event Type + Deal Amount + Close Date" },
        { id: "d", text: "Rep Zone + Client Name + Event Date" },
      ],
      correctOptionId: "b",
      explanation: "Example: \"2026-06-15 Sarah Johnson Wedding Video + Photo\" — Event Date + Client Name + Event Type + Services. Memorize this; it's how the whole team filters and reports on deals.",
    },
    {
      id: "tw-5",
      moduleId: "module-2",
      type: "scenario",
      scenarioContext: "A non-corporate client's wedding is 3 weeks away and they just confirmed they want to book.",
      prompt: "What payment structure applies to this booking?",
      options: [
        { id: "a", text: "100% upfront, since it's within a few weeks" },
        { id: "b", text: "50% deposit now, remainder due 3 days before the shoot" },
        { id: "c", text: "50% deposit now, remainder due the day of the shoot" },
        { id: "d", text: "No deposit needed until after the shoot" },
      ],
      correctOptionId: "b",
      explanation: "Non-corporate policy is 50% deposit to lock the date, with the remainder due 3 days before the shoot. Only bookings inside the rush window (under 7 days out) require 100% upfront.",
    },
    {
      id: "tw-6",
      moduleId: "module-2",
      type: "single",
      prompt: "A rush booking comes in — the shoot is 5 days away. What payment is required?",
      options: [
        { id: "a", text: "50% deposit, balance 3 days before the shoot" },
        { id: "b", text: "100% payment upfront" },
        { id: "c", text: "25% deposit to hold the date" },
        { id: "d", text: "Payment can wait until after the shoot" },
      ],
      correctOptionId: "b",
      explanation: "Any booking inside 7 days of the event date is a rush booking and requires 100% payment upfront — no exceptions without manager approval.",
    },
    {
      id: "tw-7",
      moduleId: "module-2",
      type: "single",
      prompt: "You just sent a client their payment link via OpenPhone. What must you never include in that message?",
      options: [
        { id: "a", text: "The invoice total" },
        { id: "b", text: "The HoneyBook access code" },
        { id: "c", text: "Your name" },
        { id: "d", text: "The shoot date" },
      ],
      correctOptionId: "b",
      explanation: "Payment links are sent via OpenPhone, but the HoneyBook access code must never be included in that message — it's a security policy.",
    },
    {
      id: "tw-8",
      moduleId: "module-2",
      type: "multi",
      prompt: "Which of these are required fields when logging a payment in the Revenue Sheet? (Select all that apply.)",
      options: [
        { id: "a", text: "Amount paid" },
        { id: "b", text: "Date paid" },
        { id: "c", text: "Payment method" },
        { id: "d", text: "Client's home address" },
      ],
      correctOptionIds: ["a", "b", "c"],
      explanation: "Revenue Sheet fields are: Amount paid, Date paid, Date due, Date closed, Payment method, and Payment plan. A home address isn't part of revenue tracking.",
    },
    {
      id: "tw-9",
      moduleId: "module-2",
      type: "single",
      prompt: "How soon after initial contact should a standard follow-up go out if you haven't heard back?",
      options: [
        { id: "a", text: "Same day, within the hour" },
        { id: "b", text: "2–3 days later" },
        { id: "c", text: "1 week later" },
        { id: "d", text: "Only if the client follows up first" },
      ],
      correctOptionId: "b",
      explanation: "Standard follow-up timing is 2–3 days after initial contact. If the event is within 7 days, that shifts to an urgent follow-up instead.",
    },
    {
      id: "tw-10",
      moduleId: "module-2",
      type: "single",
      prompt: "In OpenPhone, a client's name is highlighted yellow. What does that indicate?",
      options: [
        { id: "a", text: "The client cancelled their shoot" },
        { id: "b", text: "The client has paid in full" },
        { id: "c", text: "The client is pending — 50% paid or showing strong intent" },
        { id: "d", text: "The client hasn't been contacted yet" },
      ],
      correctOptionId: "c",
      explanation: "Yellow is the pending-client indicator: 50% paid or strong intent to book. Always read the OpenPhone conversation summary to confirm where they actually stand before your next message.",
    },
  ],
};
