import type { Quiz } from "../types";

export const quizObjectionHandling: Quiz = {
  id: "quiz-objection-handling",
  title: "Objection Handling Quiz",
  description: "10 questions on rebuttals, discount discipline, urgency strategy, and the two live scenarios.",
  moduleIds: ["module-4"],
  passThreshold: 0.8,
  resetModules: ["module-4"],
  questions: [
    {
      id: "oh-1",
      moduleId: "module-4",
      type: "single",
      prompt: "What is the maximum discount a rep is ever allowed to offer off the pricing calculator?",
      options: [
        { id: "a", text: "10%" },
        { id: "b", text: "15%" },
        { id: "c", text: "20%" },
        { id: "d", text: "There's no cap, use your judgment" },
      ],
      correctOptionId: "c",
      explanation: "20% is the hard ceiling off the pricing calculator output — never go below that, regardless of how much a client pushes.",
    },
    {
      id: "oh-2",
      moduleId: "module-4",
      type: "scenario",
      scenarioContext: "A client says: \"The price is too high.\"",
      prompt: "What's the correct first move?",
      options: [
        { id: "a", text: "Immediately offer the maximum 20% discount" },
        { id: "b", text: "Break down the scope of what's included and reframe the value" },
        { id: "c", text: "Tell them to think it over and hang up" },
        { id: "d", text: "Match whatever price they say a competitor quoted" },
      ],
      correctOptionId: "b",
      explanation: "The price objection playbook is: acknowledge, break down the scope (what's actually included), then reframe the value — discount is the last lever, not the first.",
    },
    {
      id: "oh-3",
      moduleId: "module-4",
      type: "single",
      prompt: "According to the Golden Rule of Objections, what does an objection actually mean?",
      options: [
        { id: "a", text: "The client is rejecting the deal outright" },
        { id: "b", text: "A question in disguise — they want to understand why it's worth it" },
        { id: "c", text: "The client wants to negotiate on everything" },
        { id: "d", text: "The rep did something wrong" },
      ],
      correctOptionId: "b",
      explanation: "\"An objection is not a rejection. It's a question in disguise.\" Answer the real underlying question with confidence and proof.",
    },
    {
      id: "oh-4",
      moduleId: "module-4",
      type: "multi",
      prompt: "Which of these are legitimate reasons Beige gives for being worth more than a cheaper competitor like Snapper? (Select all that apply.)",
      options: [
        { id: "a", text: "$1M liability insurance" },
        { id: "b", text: "Beige Guarantee (backup crew on standby)" },
        { id: "c", text: "Raw content ownership / IP rights" },
        { id: "d", text: "Beige is simply a bigger company" },
      ],
      correctOptionIds: ["a", "b", "c"],
      explanation: "The concrete differentiators are $1M insurance, the Beige Guarantee, and raw content/IP ownership — vague size claims (\"we're just better\") land flat with analytical clients.",
    },
    {
      id: "oh-5",
      moduleId: "module-4",
      type: "single",
      prompt: "What is the \"soft hold\" technique used for?",
      options: [
        { id: "a", text: "Putting a client on hold during a call" },
        { id: "b", text: "Reserving a date for a hesitant client without a deposit, while still driving urgency" },
        { id: "c", text: "Delaying a proposal until the client is ready" },
        { id: "d", text: "Refusing to negotiate on price" },
      ],
      correctOptionId: "b",
      explanation: "A soft hold assumes the sale even when there's a barrier — it reserves the date informally while keeping urgency and a concrete timeline alive.",
    },
    {
      id: "oh-6",
      moduleId: "module-4",
      type: "single",
      prompt: "When should you try to deliver the exact price to a client, if possible?",
      options: [
        { id: "a", text: "As early as possible, before they ask" },
        { id: "b", text: "Wait for the client to ask, then say it with confidence" },
        { id: "c", text: "Only in writing, never verbally" },
        { id: "d", text: "Never state a price on a call" },
      ],
      correctOptionId: "b",
      explanation: "Where possible, let the client ask for the number first, then deliver it confidently — leading with price before value is established weakens your position.",
    },
    {
      id: "oh-7",
      moduleId: "module-4",
      type: "scenario",
      scenarioContext: "In the Tough Corporate Call scenario, Jordan mentions he's used Snapper before and it was cheaper.",
      prompt: "What's the strongest response?",
      options: [
        { id: "a", text: "\"We're just a better company overall, trust me.\"" },
        { id: "b", text: "We carry $1M liability insurance, guarantee a backup crew, and deliver all raw footage — and tie it to the risk of a large event like his" },
        { id: "c", text: "Immediately offer to beat Snapper's price" },
        { id: "d", text: "Avoid the topic and change the subject" },
      ],
      correctOptionId: "b",
      explanation: "This deploys the Beige trifecta — insurance, guarantee, raw content — and ties it directly to the risk context of his specific event. Vague superiority claims don't land with analytical corporate buyers.",
    },
    {
      id: "oh-8",
      moduleId: "module-4",
      type: "single",
      prompt: "In the Wedding Budget Pushback scenario, what's the correct discount sequence when a client says the quote is out of budget?",
      options: [
        { id: "a", text: "Offer the full 20% immediately to close fast" },
        { id: "b", text: "Refuse any discount" },
        { id: "c", text: "Start around 10%, and only move closer to the 20% ceiling if they push again" },
        { id: "d", text: "Offer 30% since it's a wedding" },
      ],
      correctOptionId: "c",
      explanation: "Start at 10% (the Event 4B script), and only escalate toward the 20% ceiling if there's genuine further pushback — never jump straight to your maximum, and never exceed it.",
    },
    {
      id: "oh-9",
      moduleId: "module-4",
      type: "single",
      prompt: "A client says they're comparing you to another company. What should you say first?",
      options: [
        { id: "a", text: "\"Who are you comparing us to? Their prices are probably better.\"" },
        { id: "b", text: "Acknowledge it, then reinforce the Beige Guarantee, $1M insurance, and raw content ownership" },
        { id: "c", text: "Immediately drop the price to win the comparison" },
        { id: "d", text: "End the call and follow up later" },
      ],
      correctOptionId: "b",
      explanation: "Acknowledge the comparison is reasonable, then reinforce the concrete differentiators — insurance, guarantee, raw content — rather than racing to match an unknown competitor's price.",
    },
    {
      id: "oh-10",
      moduleId: "module-4",
      type: "single",
      prompt: "When is a paid-in-full discount the right tool to offer?",
      options: [
        { id: "a", text: "Never — Beige doesn't offer this" },
        { id: "b", text: "As an incentive to get the client to pay the full amount upfront" },
        { id: "c", text: "Only for rush bookings" },
        { id: "d", text: "Automatically applied to every invoice" },
      ],
      correctOptionId: "b",
      explanation: "The paid-in-full discount is a deliberate incentive: offer it to move a hesitant client toward paying the entire amount today instead of a deposit.",
    },
  ],
};
