import type { Quiz } from "../types";

export const quizScriptsEventTypes: Quiz = {
  id: "quiz-scripts-event-types",
  title: "Scripts & Event Types Quiz",
  description: "10 questions covering the universal call framework and scripts for all 9 Beige event types.",
  moduleIds: ["module-3"],
  passThreshold: 0.8,
  resetModules: ["module-3"],
  heroImage: "/images/quiz-scripts-event-types-hero.png",
  questions: [
    {
      id: "se-1",
      moduleId: "module-3",
      type: "ordering",
      prompt: "Put the Universal Call Script Framework in the correct order.",
      steps: ["Intro", "Value Propositions", "Discovery Questions", "Wrap-Up", "Closing"],
      explanation: "Every call — regardless of event type — follows this structure: greet and identify yourself, lead with value/credibility, ask discovery questions, wrap up with a proposal promise, then close with a follow-up time.",
    },
    {
      id: "se-2",
      moduleId: "module-3",
      type: "scenario",
      scenarioContext: "A client asks if you can just do photography for their Quinceañera — not video.",
      characterImage: "/images/mathieu-asking.png",
      sceneImage: "/images/scene-wedding-budget-EN.png",
      prompt: "What's the right response?",
      options: [
        { id: "a", text: "\"Sure, we only do photo for that then.\" and move on" },
        { id: "b", text: "\"Absolutely, we'd be happy to offer a discounted package deal for both!\"" },
        { id: "c", text: "\"We don't offer photography on its own.\"" },
        { id: "d", text: "Ask them to decide and call back later" },
      ],
      correctOptionId: "b",
      explanation: "Private event scripts are built to upsell the package: whenever a client asks for just one service, offer the discounted video + photo package deal before accepting the single-service request.",
    },
    {
      id: "se-3",
      moduleId: "module-3",
      type: "matching",
      prompt: "Match each event type to its correct value-prop lead-in.",
      pairs: [
        { left: "Corporate Event", right: "Brand credibility — Amazon, Chase, Orange Theory, DHL, Rolls Royce" },
        { left: "Wedding", right: "Congratulate the client first, then discover their vision" },
        { left: "Memorial", right: "Open with genuine condolences" },
        { left: "Podcast", right: "Name-drop past collaborations like Steve Aoki and Natasha Graziano" },
      ],
      explanation: "Each event type opens with a different emotional register: corporate leads with brand proof, weddings with congratulations, memorials with condolences, and podcasts with relevant creator credibility.",
    },
    {
      id: "se-4",
      moduleId: "module-3",
      type: "single",
      prompt: "For a wedding video, what are the two standard length options you present to the client?",
      options: [
        { id: "a", text: "30–60 second reel or 1–2 minute promo" },
        { id: "b", text: "4–7 minute highlight video or 20–30 minute feature video" },
        { id: "c", text: "5–10 minute short film or full ceremony recording" },
        { id: "d", text: "10 minutes only, no options" },
      ],
      correctOptionId: "b",
      explanation: "Weddings offer a 4–7 minute highlight video or a 20–30 minute feature video — most clients end up going for both.",
    },
    {
      id: "se-5",
      moduleId: "module-3",
      type: "single",
      prompt: "What is the starting price for a music video, per the training?",
      options: [
        { id: "a", text: "$1,000" },
        { id: "b", text: "$1,500" },
        { id: "c", text: "$2,500" },
        { id: "d", text: "$5,000" },
      ],
      correctOptionId: "c",
      explanation: "Music videos start at $2,500. You can flex toward a lower number like $1,500 to build a relationship with the right client, but always know your floor first.",
    },
    {
      id: "se-6",
      moduleId: "module-3",
      type: "single",
      prompt: "For a corporate event photo package, roughly how many edited photos per hour of coverage should you tell the client to expect?",
      options: [
        { id: "a", text: "10 per hour" },
        { id: "b", text: "25 per hour" },
        { id: "c", text: "50 per hour" },
        { id: "d", text: "100 per hour" },
      ],
      correctOptionId: "c",
      explanation: "Standard guidance is about 50 edited photos per hour of coverage — use that to give the client a concrete total for their event length.",
    },
    {
      id: "se-7",
      moduleId: "module-3",
      type: "single",
      prompt: "What tone should you strike throughout a memorial script?",
      options: [
        { id: "a", text: "Efficient and fast-moving, to respect their time" },
        { id: "b", text: "Compassionate, unhurried, and never pushy about budget or dates" },
        { id: "c", text: "Upbeat and celebratory, like a private event" },
        { id: "d", text: "Formal and transactional" },
      ],
      correctOptionId: "b",
      explanation: "Memorials are the most emotionally sensitive script Beige has. Stay compassionate and unhurried, and never push on budget or timing.",
    },
    {
      id: "se-8",
      moduleId: "module-3",
      type: "multi",
      prompt: "Which affirmation-style phrases should you sprinkle in while asking discovery questions? (Select all that apply.)",
      options: [
        { id: "a", text: "\"Great\"" },
        { id: "b", text: "\"Awesome\"" },
        { id: "c", text: "\"Absolutely\"" },
        { id: "d", text: "\"Whatever works for you, I guess\"" },
      ],
      correctOptionIds: ["a", "b", "c"],
      explanation: "Filler affirmations like \"great,\" \"awesome,\" and \"absolutely\" keep discovery calls warm and responsive. Flat or noncommittal language undercuts the energy the script is built around.",
    },
    {
      id: "se-9",
      moduleId: "module-3",
      type: "single",
      prompt: "A former client that Kawser used to personally handle texts your line for the first time. What's the correct rebuttal script?",
      options: [
        { id: "a", text: "Ignore it — that client isn't yours" },
        { id: "b", text: "\"Just wanted to give you a heads up that we're now using a company cell line for better service and support.\"" },
        { id: "c", text: "Ask them to contact Kawser directly" },
        { id: "d", text: "Introduce yourself as a brand-new hire with no context" },
      ],
      correctOptionId: "b",
      explanation: "This is the Kawser's Contacts Rebuttal from the SMS & Voicemail Quick Reference — it smoothly reframes the new number as a company-wide service upgrade.",
    },
    {
      id: "se-10",
      moduleId: "module-3",
      type: "single",
      prompt: "A client asks about surcharges for booking on a holiday. What's the correct response?",
      options: [
        { id: "a", text: "There's a 15% holiday surcharge" },
        { id: "b", text: "Unlike other companies, Beige doesn't charge anything additional for holidays" },
        { id: "c", text: "Holidays aren't available for booking" },
        { id: "d", text: "It depends on the rep's discretion" },
      ],
      correctOptionId: "b",
      explanation: "The Holiday Clause is a differentiator and a closer: no holiday surcharge, unlike most competitors — offer to waive it as a reason to book now.",
    },
    {
      id: "se-11",
      moduleId: "module-3",
      type: "scenario",
      scenarioContext: "A budget-conscious client wants both photo and video coverage but is worried about the cost of booking two separate creators.",
      characterImage: "/images/mathieu-worried.png",
      sceneImage: "/images/scene-niehodbbx-EN.png",
      prompt: "What option should you offer alongside separate dedicated photo + video crews?",
      options: [
        { id: "a", text: "A single hybrid creator who covers both photo and video at a lower combined rate" },
        { id: "b", text: "Tell them to pick only one service" },
        { id: "c", text: "Refer them to a competitor" },
        { id: "d", text: "Only offer the full separate-crew rate, no alternative" },
      ],
      correctOptionId: "a",
      explanation: "A hybrid creator — one person shooting both photo and video — is a real, lower-cost option to offer budget-conscious clients instead of losing the deal outright or booking two full separate crews.",
    },
  ],
};
