import type { Quiz } from "../types";

export const quizToolsWorkflow: Quiz = {
  id: "quiz-tools-workflow",
  title: "Tools & Workflow Quiz",
  description: "10 questions on the lead-to-cash workflow: Thumbtack, OpenPhone, beige.app, GHL, and team communication.",
  moduleIds: ["module-2"],
  passThreshold: 0.8,
  resetModules: ["module-2"],
  heroImage: "/images/quiz-tools-workflow-hero.png",
  questions: [
    {
      id: "tw-1",
      moduleId: "module-2",
      type: "ordering",
      topicImage: "/images/icon-checklist-verify.png",
      prompt: "Put the Lead Hit Funnel steps in the correct order, from a new lead arriving to a call being scheduled.",
      steps: [
        "Lead arrives via Thumbtack",
        "Notify the Inbound Slack channel — team decides to take the lead",
        "Apply the correct template text and categorize the shoot type",
        "Assign a rep in OpenPhone and schedule the discovery call",
      ],
      explanation: "This is the exact 4-step Lead Hit Funnel: the lead lands, the team claims it in Slack, the rep applies the right template, then a rep is assigned and the discovery call gets booked.",
    },
    {
      id: "tw-2",
      moduleId: "module-2",
      type: "single",
      topicImage: "/images/icon-lead-inquiry.png",
      prompt: "A new Thumbtack lead just came in. What should you do before anything else?",
      options: [
        { id: "a", text: "Finish your current follow-up call first, then respond" },
        { id: "b", text: "Respond to the new lead immediately, before any other task" },
        { id: "c", text: "Wait for Kawser to assign it to you" },
        { id: "d", text: "Check GHL to see if it's a repeat client first" },
      ],
      correctOptionId: "b",
      explanation: "The key policy is: always respond to new leads before doing anything else. Speed on first contact is everything.",
    },
    {
      id: "tw-3",
      moduleId: "module-2",
      type: "matching",
      topicImage: "/images/icon-team-comms.png",
      prompt: "Match each communication platform to its correct use at Beige.",
      pairs: [
        { left: "Slack", right: "Inbound Sales team communication only" },
        { left: "Discord", right: "UserSuccess, production, and post-production communication" },
        { left: "OpenPhone", right: "Client-facing calls and texts" },
        { left: "GHL", right: "Lead and pipeline tracking" },
      ],
      explanation: "Slack is reserved for Inbound Sales; everything else (UserSuccess, production, post-production) runs through Discord. OpenPhone is the client-facing line, GHL is the CRM.",
    },
    {
      id: "tw-4",
      moduleId: "module-2",
      type: "single",
      topicImage: "/images/icon-pipeline-flow.png",
      prompt: "A lead needs to move from the General Events Pipeline into a rep's own pipeline in GHL. What's the correct process?",
      options: [
        { id: "a", text: "Open the lead, switch the Pipeline dropdown to the rep's pipeline, assign them as Owner (or Follower), set the first stage, and click Update" },
        { id: "b", text: "Tell the rep the lead's name over Slack and let them find it themselves" },
        { id: "c", text: "Copy the lead's details into a new pipeline by hand" },
        { id: "d", text: "Leave it in General — every rep can already see everything in there" },
      ],
      correctOptionId: "a",
      explanation: "Pipeline dropdown, switch to the rep's pipeline, assign Owner/Follower, set the first stage, click Update. Once you do, the lead disappears from General and shows up in that rep's private pipeline.",
    },
    {
      id: "tw-5",
      moduleId: "module-2",
      type: "scenario",
      scenarioContext: "A non-corporate client's wedding is 3 weeks away and they just confirmed they want to book.",
      characterImage: "/images/mathieu-neutral.png",
      sceneImage: "/images/scene-niehodbbx-EN.png",
      prompt: "What payment structure applies to this booking?",
      options: [
        { id: "a", text: "100% upfront, since it's within a few weeks" },
        { id: "b", text: "50% deposit now, remainder due 3 days before the shoot" },
        { id: "c", text: "50% deposit now, remainder due the day of the shoot" },
        { id: "d", text: "No deposit needed until after the shoot" },
      ],
      correctOptionId: "b",
      explanation: "Non-corporate policy is 50% deposit to lock the date, with the remainder due 3 days before the shoot. Only bookings inside the rush window (under 7 days out) require 100% upfront.",
    },
    {
      id: "tw-6",
      moduleId: "module-2",
      type: "single",
      topicImage: "/images/icon-urgency-clock.png",
      prompt: "A rush booking comes in — the shoot is 5 days away. What payment is required?",
      options: [
        { id: "a", text: "50% deposit, balance 3 days before the shoot" },
        { id: "b", text: "100% payment upfront" },
        { id: "c", text: "25% deposit to hold the date" },
        { id: "d", text: "Payment can wait until after the shoot" },
      ],
      correctOptionId: "b",
      explanation: "Any booking inside 7 days of the event date is a rush booking and requires 100% payment upfront — no exceptions without manager approval.",
    },
    {
      id: "tw-7",
      moduleId: "module-2",
      type: "single",
      topicImage: "/images/icon-payment.png",
      prompt: "A client just signed their beige.app quote. How do you get them their payment instructions?",
      options: [
        { id: "a", text: "Send the Zelle email or tag (accounting@beigecorporation.io / @beigecorp) directly over OpenPhone" },
        { id: "b", text: "Generate a separate payment link in HoneyBook" },
        { id: "c", text: "Wait for them to ask how to pay" },
        { id: "d", text: "Email a PDF invoice with wire instructions" },
      ],
      correctOptionId: "a",
      explanation: "Payment now runs through Zelle by default — text the Zelle email or @beigecorp tag directly once the quote is signed. There's no separate payment-link tool in the current workflow.",
    },
    {
      id: "tw-8",
      moduleId: "module-2",
      type: "multi",
      topicImage: "/images/icon-checklist-verify.png",
      prompt: "Which of these are real Revenue Sheet fields you fill in during Shoot Activation & Handoff? (Select all that apply.)",
      options: [
        { id: "a", text: "Invoice Number" },
        { id: "b", text: "Rep Name" },
        { id: "c", text: "Payment Method" },
        { id: "d", text: "Client's Instagram handle" },
      ],
      correctOptionIds: ["a", "b", "c"],
      explanation: "The Revenue Sheet covers Client Name, Source, Status, Payment Terms, City/State, Category, Email, Phone, Total Deal, Amount Paid, Date Amount Paid, Amount Due, Date Amount Due, Date Closed, Shoot Date, Invoice Number, Invoice Link, Payment Method, and Rep Name — social media handles aren't part of it.",
    },
    {
      id: "tw-9",
      moduleId: "module-2",
      type: "single",
      topicImage: "/images/icon-followup-message.png",
      prompt: "How soon after initial contact should a standard follow-up go out if you haven't heard back?",
      options: [
        { id: "a", text: "Same day, within the hour" },
        { id: "b", text: "2–3 days later" },
        { id: "c", text: "1 week later" },
        { id: "d", text: "Only if the client follows up first" },
      ],
      correctOptionId: "b",
      explanation: "Standard follow-up timing is 2–3 days after initial contact. If the event is within 7 days, that shifts to an urgent follow-up instead.",
    },
    {
      id: "tw-10",
      moduleId: "module-2",
      type: "single",
      topicImage: "/images/icon-lead-inquiry.png",
      prompt: "In OpenPhone, a client's name is highlighted yellow. What does that indicate?",
      options: [
        { id: "a", text: "The client cancelled their shoot" },
        { id: "b", text: "The client has paid in full" },
        { id: "c", text: "The client is pending — 50% paid or showing strong intent" },
        { id: "d", text: "The client hasn't been contacted yet" },
      ],
      correctOptionId: "c",
      explanation: "Yellow is the pending-client indicator: 50% paid or strong intent to book. Always read the OpenPhone conversation summary to confirm where they actually stand before your next message.",
    },
  ],
};
